### ISSUE TITLE
Implementation Error

### ISSUE THREAD

**Issue by CDoganLTX** [wk989898/ARES-implement#2]
Model predicts the same number after the third epoch - I tried on a much larger dataset of structures (20,000) to train and this was the case.

**Comment by CDoganLTX** [comment]
I also tried changing various parameters such as batch size, LR etc. Always predicts the same RMSD for any structure provided.

**Comment by FlorianWieser1** [comment]
I have the same issue. No matter what I do, RMSDs of various RNA structures will only differ in the fourth decimal place..

**Comment by wk989898** [comment]
Please try official code.
