### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by zongzhao23** [wk989898/ARES-implement#8]
I find the code "mius = [12/11*i for i in range(12)] G = [p * np.square(np.exp((Rab-miu))*q) for miu in mius]" is different from the description in the original paper. Maybe it should be "G = [p * np.exp(-np.square(Rab-miu)/2) for miu in mius]" ? I'm not sure if my code is correct, and I hope to have further communication with you.

**Comment by wk989898** [comment]
Thank you, I have fixed it.
